//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadBetterTogether
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompagnySiteSet
    {
        public int Id { get; set; }
        public int TogetherCompagnyId { get; set; }
        public string adresse { get; set; }
    
        public virtual TogetherCompagnySet TogetherCompagnySet { get; set; }
    }
}
