//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadBetterTogether
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TogetherContext : DbContext
    {
        public TogetherContext()
            : base("name=TogetherContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdressesSet> AdressesSet { get; set; }
        public virtual DbSet<AdressesSet_HomeAdress> AdressesSet_HomeAdress { get; set; }
        public virtual DbSet<AdressesSet_WorkAdress> AdressesSet_WorkAdress { get; set; }
        public virtual DbSet<CompagnySiteSet> CompagnySiteSet { get; set; }
        public virtual DbSet<HomeAdressSet> HomeAdressSet { get; set; }
        public virtual DbSet<PostSet> PostSet { get; set; }
        public virtual DbSet<RoadTeamSet> RoadTeamSet { get; set; }
        public virtual DbSet<TogetherCarsSet> TogetherCarsSet { get; set; }
        public virtual DbSet<TogetherCompagnySet> TogetherCompagnySet { get; set; }
        public virtual DbSet<TogetherUsersSet> TogetherUsersSet { get; set; }
        public virtual DbSet<TogetherUsersSet_TogetherDrivers> TogetherUsersSet_TogetherDrivers { get; set; }
        public virtual DbSet<WorkAdressSet> WorkAdressSet { get; set; }
    }
}
