//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadBetterTogether
{
    using System;
    using System.Collections.Generic;
    
    public partial class TogetherUsersSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TogetherUsersSet()
        {
            this.AdressesSet = new HashSet<AdressesSet>();
        }
    
        public int Id { get; set; }
        public string firstname { get; set; }
        public string name { get; set; }
        public int age { get; set; }
        public string email { get; set; }
        public bool goingMode { get; set; }
        public int TogetherDriversId { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public bool actif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdressesSet> AdressesSet { get; set; }
        public virtual TogetherUsersSet_TogetherDrivers TogetherUsersSet_TogetherDrivers { get; set; }
    }
}
