//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadBetterTogether
{
    using System;
    using System.Collections.Generic;
    
    public partial class TogetherCarsSet
    {
        public int Id { get; set; }
        public string immatriculation { get; set; }
        public string marque { get; set; }
        public string annee { get; set; }
        public Nullable<int> RoadTeamId { get; set; }
        public int places { get; set; }
        public int TogetherDrivers_Id { get; set; }
    
        public virtual TogetherUsersSet_TogetherDrivers TogetherUsersSet_TogetherDrivers { get; set; }
    }
}
