//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadBetterTogether.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities3 : DbContext
    {
        public Entities3()
            : base("name=Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdressesSet> AdressesSet { get; set; }
        public DbSet<CompagnySiteSet> CompagnySiteSet { get; set; }
        public DbSet<PostSet> PostSet { get; set; }
        public DbSet<RoadTeamSet> RoadTeamSet { get; set; }
        public DbSet<TogetherCarsSet> TogetherCarsSet { get; set; }
        public DbSet<TogetherCompagnySet> TogetherCompagnySet { get; set; }
        public DbSet<TogetherUsersSet> TogetherUsersSet { get; set; }
        public DbSet<TogetherUsersSet_TogetherDrivers> TogetherUsersSet_TogetherDrivers { get; set; }
    }
}
